<div class="page-header"><h3>Tramites</h3></div>
    <table id="formatotabla" class="display">
        <thead>
            <tr>

                <th>&nbsp;</th>
                <th>id</th>
                <th>titulo</th>
                <th>fecha</th>
                <th>estado</th>
                <th>&nbsp;</th>

            </tr>
        </thead>
        <tbody>
        <?php
        if (count($this->tramites)) {
            echo $this->partialLoop('admin/partials/listar-row-tramite.phtml', $this->tramites); 
        }
        ?>
        </tbody>
    </table>
