<h1 class="outOfView">Argentina Comparte - Noticia: <?php echo $this->news['title'] ?> </h1>
<?php $this->placeholder('news')->captureStart(); ?>
    <?php
        $image = count($this->news['Images'])
            ? '/uploads/tmp/' . $this->news['id'] . '/' . $this->news['Images'][0]['name']
            : '/img/notfound.jpg';
        
        echo $this->multimediaBox(
            array(
                'file' => $image,
                'type' => 'image',
                'title' => $this->news['title'],
                'copy' => $this->news['body'],
                'date' => $this->news['creation_date'],
            )
        );
    ?>
<?php $this->placeholder('news')->captureEnd(); ?>
